"""MeanFlow Policy — Flow-matching generative policy for HFT.

Implements a conditional flow-matching model where the policy action
is generated by transporting noise through a learned velocity field
conditioned on market state.

The flow matching objective is:
    L = E_{t, x_0, x_1} || v_theta(x_t, t, cond) - (x_1 - x_0)||^2

where x_0 ~ N(0,I), x_1 is the expert action, and x_t = (1-t)*x_0 + t*x_1.
"""

import numpy as np
from typing import Optional, Dict


class MeanFlowPolicy:
    """Conditional flow-matching policy for continuous actions in HFT.

    Architecture:
        obs -> [FiLM-conditioned MLP] -> velocity field v(x_t, t)
        x_0 ~ N(0, I), x_1 = expert_action
        x_t = (1-t)*x_0 + t*x_1
        sampled_action = integrate velocity field from t=0 to t=1
    """

    def __init__(
        self,
        obs_dim: int,
        act_dim: int,
        hidden_sizes: tuple = (128, 128, 64),
        n_flow_steps: int = 10,
    ):
        self.obs_dim = obs_dim
        self.act_dim = act_dim
        self.hidden_sizes = hidden_sizes
        self.n_flow_steps = n_flow_steps

        # Velocity network: input = [x_t, t, obs], output = velocity
        vel_input_dim = act_dim + 1 + obs_dim
        self.vel_weights: list = []
        self.vel_biases: list = []
        prev_dim = vel_input_dim
        for h in hidden_sizes:
            scale = np.sqrt(2.0 / prev_dim)
            self.vel_weights.append(np.random.randn(prev_dim, h) * scale)
            self.vel_biases.append(np.zeros(h))
            prev_dim = h
        # Output: velocity in action space
        self.vel_weights.append(np.random.randn(prev_dim, act_dim) * np.sqrt(2.0 / prev_dim))
        self.vel_biases.append(np.zeros(act_dim))

        # FiLM conditioning on observation
        self.film_gamma = np.ones(hidden_sizes[-1])
        self.film_beta = np.zeros(hidden_sizes[-1])
        self.W_film = np.random.randn(obs_dim, hidden_sizes[-1]) * np.sqrt(2.0 / obs_dim)
        self.b_film = np.zeros(hidden_sizes[-1])

    @property
    def n_params(self) -> int:
        """Total number of trainable parameters."""
        total = 0
        for w, b in zip(self.vel_weights, self.vel_biases):
            total += w.size + b.size
        total += self.film_gamma.size + self.film_beta.size
        total += self.W_film.size + self.b_film.size
        return total

    def _velocity_network(self, x_t: np.ndarray, t: float, obs: np.ndarray) -> np.ndarray:
        """Compute velocity field v(x_t, t, obs)."""
        t_arr = np.array([t])
        x_in = np.concatenate([x_t, t_arr, obs])
        for i, (w, b) in enumerate(zip(self.vel_weights, self.vel_biases)):
            x_in = x_in @ w + b
            if i < len(self.vel_weights) - 1:
                x_in = np.tanh(x_in)
                # Apply FiLM on the last hidden layer
                if i == len(self.vel_weights) - 2:
                    gamma = obs @ self.W_film + self.b_film
                    gamma = gamma * self.film_gamma + self.film_beta
                    x_in = gamma * x_in
        return x_in

    def flow_loss(self, obs: np.ndarray, expert_action: np.ndarray) -> float:
        """Compute flow-matching loss: ||v_theta - (x_1 - x_0)||^2.

        Args:
            obs: observation vector
            expert_action: expert action x_1

        Returns:
            scalar loss
        """
        t = np.random.uniform(0, 1)
        x_0 = np.random.randn(self.act_dim)
        x_t = (1 - t) * x_0 + t * expert_action
        target_velocity = expert_action - x_0
        pred_velocity = self._velocity_network(x_t, t, obs)
        loss = float(np.mean((pred_velocity - target_velocity) ** 2))
        return loss

    def act(self, obs: np.ndarray, deterministic: bool = False) -> np.ndarray:
        """Sample action via Euler integration of the flow ODE.

        dx/dt = v_theta(x_t, t, obs), from t=0 (noise) to t=1 (action)
        """
        x = np.random.randn(self.act_dim) if not deterministic else np.zeros(self.act_dim)
        dt = 1.0 / self.n_flow_steps
        for step in range(self.n_flow_steps):
            t = step * dt
            v = self._velocity_network(x, t, obs)
            x = x + v * dt
        return x

    def get_params(self) -> Dict[str, list]:
        """Get all trainable parameters."""
        return {
            "vel_weights": [w.copy() for w in self.vel_weights],
            "vel_biases": [b.copy() for b in self.vel_biases],
            "film_gamma": self.film_gamma.copy(),
            "film_beta": self.film_beta.copy(),
            "W_film": self.W_film.copy(),
            "b_film": self.b_film.copy(),
        }

    def set_params(self, params: Dict[str, list]) -> None:
        """Set all trainable parameters."""
        self.vel_weights = [w.copy() for w in params["vel_weights"]]
        self.vel_biases = [b.copy() for b in params["vel_biases"]]
        self.film_gamma = params["film_gamma"].copy()
        self.film_beta = params["film_beta"].copy()
        self.W_film = params["W_film"].copy()
        self.b_film = params["b_film"].copy()
